### ISSUE TITLE
Glass Shard & Silk Touch

### ISSUE THREAD

**Issue by JLUsr** [MonsterTrex/ReCraft#1]
I would imagine this is not intended; however, breaking a glass block with SikTouch will still drop Glass Shards along with the glass block, resulting in infinite Glass Shards.

**Comment by MonsterTrex** [comment]
Does this apply only to the vanilla glass block? That might have slipped past me when testing. Will look into this as soon as possible

**Comment by JLUsr** [comment]
Only the vanilla glass block. When mining frosted glass no shards were produced.

**Comment by MonsterTrex** [comment]
Thank you for reporting this issue. I believe it to be fixed now in the latest 0.2 update.
